import { Recipe } from './types';

export const DEFAULT_RECIPES: Omit<Recipe, 'id'>[] = [
  // ─── APÉRO ───────────────────────────────────────────────
  {
    name: 'Bruschetta tomates basilic',
    emoji: '🍞',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 1, unit: 'unité' },
      { foodId: 'basilic', foodName: 'Basilic', quantity: 5, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Faire griller les tranches de pain.',
      'Frotter chaque tranche avec une gousse d\'ail.',
      'Couper les tomates en dés, assaisonner avec sel, poivre et basilic.',
      'Disposer les tomates sur le pain, arroser d\'huile d\'olive.',
    ],
  },
  {
    name: 'Guacamole maison',
    emoji: '🥑',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'tomate', foodName: 'Tomate', quantity: 1, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'coriandre', foodName: 'Coriandre', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Écraser les avocats à la fourchette.',
      'Ajouter la tomate coupée en dés, l\'oignon ciselé.',
      'Presser le citron, ajouter la coriandre et le sel.',
      'Mélanger et servir immédiatement.',
    ],
  },
  {
    name: 'Houmous express',
    emoji: '🫘',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'pois-chiches', foodName: 'Pois chiches', quantity: 400, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 40, unit: 'ml' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 3, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Égoutter et rincer les pois chiches.',
      'Mixer avec l\'ail, le jus de citron, l\'huile et le cumin.',
      'Saler, mixer jusqu\'à consistance crémeuse.',
      'Servir avec un filet d\'huile d\'olive.',
    ],
  },

  // ─── ENTRÉES ─────────────────────────────────────────────
  {
    name: 'Velouté de carottes au cumin',
    emoji: '🥕',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'carotte', foodName: 'Carotte', quantity: 6, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 100, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon émincé dans le beurre.',
      'Ajouter les carottes en rondelles et le cumin.',
      'Couvrir d\'eau avec le bouillon cube, cuire 20 min.',
      'Mixer finement, incorporer la crème fraîche.',
    ],
  },
  {
    name: 'Salade chèvre chaud & lardons',
    emoji: '🥗',
    category: 'Entrées',
    servings: 2,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'salade', foodName: 'Salade verte', quantity: 1, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 150, unit: 'g' },
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'vinaigre', foodName: 'Vinaigre', quantity: 20, unit: 'ml' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Faire revenir les lardons à la poêle.',
      'Poser le fromage de chèvre sur les tranches de pain et passer au gril.',
      'Préparer la vinaigrette moutarde/vinaigre/huile.',
      'Dresser la salade, ajouter les lardons, les toasts de chèvre chaud.',
    ],
  },

  // ─── PLATS ───────────────────────────────────────────────
  {
    name: 'Spaghetti bolognaise',
    emoji: '🍝',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 400, unit: 'g' },
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 400, unit: 'g' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 30, unit: 'g' },
      { foodId: 'herbes-provence', foodName: 'Herbes de Provence', quantity: 5, unit: 'g' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon et l\'ail émincés dans l\'huile d\'olive.',
      'Ajouter le bœuf haché, faire brunir.',
      'Incorporer les tomates concassées et le concentré, herbes, sel, poivre.',
      'Laisser mijoter 30 min à feu doux.',
      'Cuire les pâtes al dente, servir avec la sauce et le parmesan.',
    ],
  },
  {
    name: 'Curry de poulet au lait de coco',
    emoji: '🍛',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'blanc-poulet', foodName: 'Blanc de poulet', quantity: 600, unit: 'g' },
      { foodId: 'lait-coco', foodName: 'Lait de coco', quantity: 400, unit: 'ml' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'curry', foodName: 'Curry', quantity: 15, unit: 'g' },
      { foodId: 'riz-basmati', foodName: 'Riz basmati', quantity: 300, unit: 'g' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Faire revenir oignon et ail dans l\'huile.',
      'Ajouter le poulet coupé en dés, faire dorer.',
      'Saupoudrer de curry, mélanger 1 min.',
      'Verser le lait de coco, laisser mijoter 20 min.',
      'Servir avec le riz basmati cuit.',
    ],
  },
  {
    name: 'Quiche lorraine',
    emoji: '🥧',
    category: 'Plats',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'pate-brisee', foodName: 'Pâte brisée', quantity: 1, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 200, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
      { foodId: 'muscade', foodName: 'Noix de muscade', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans un moule, piquer le fond.',
      'Faire revenir les lardons, les disposer sur la pâte.',
      'Battre les œufs avec la crème et le lait, sel, muscade.',
      'Verser l\'appareil, saupoudrer de fromage râpé.',
      'Cuire 35 min jusqu\'à ce que la quiche soit dorée.',
    ],
  },
  {
    name: 'Ratatouille provençale',
    emoji: '🫕',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'aubergine', foodName: 'Aubergine', quantity: 1, unit: 'unité' },
      { foodId: 'courgette', foodName: 'Courgette', quantity: 2, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 3, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'herbes-provence', foodName: 'Herbes de Provence', quantity: 8, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 50, unit: 'ml' },
    ],
    instructions: [
      'Couper tous les légumes en dés.',
      'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
      'Ajouter les légumes par ordre de dureté (poivron, aubergine, courgette, tomate).',
      'Assaisonner avec les herbes de Provence, sel, poivre.',
      'Mijoter à couvert 30 min, puis 15 min à découvert.',
    ],
  },
  {
    name: 'Saumon à la crème et aneth',
    emoji: '🐟',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'saumon', foodName: 'Saumon', quantity: 400, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 150, unit: 'ml' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Assaisonner le saumon de sel, poivre et jus de citron.',
      'Faire cuire à la poêle dans le beurre, 4 min par côté.',
      'Réserver le saumon, déglacer avec la crème fraîche.',
      'Laisser réduire 2 min, ajouter le persil.',
      'Napper le saumon de sauce à la crème.',
    ],
  },
  {
    name: 'Omelette aux champignons',
    emoji: '🍳',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 150, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Faire revenir les champignons émincés dans le beurre.',
      'Battre les œufs avec sel, poivre et persil.',
      'Verser les œufs sur les champignons en poêle chaude.',
      'Plier l\'omelette dès que les bords sont pris.',
    ],
  },
  {
    name: 'Poulet rôti aux herbes',
    emoji: '🍗',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 70,
    isDefault: true,
    ingredients: [
      { foodId: 'poulet-entier', foodName: 'Poulet entier', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 50, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 4, unit: 'unité' },
      { foodId: 'thym', foodName: 'Thym', quantity: 5, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
      { foodId: 'sel', foodName: 'Sel', quantity: 5, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Préchauffer le four à 200°C.',
      'Badigeonner le poulet de beurre mou, ail, thym, sel.',
      'Glisser les gousses d\'ail et le laurier dans la cavité.',
      'Rôtir 1h10 en arrosant régulièrement du jus de cuisson.',
    ],
  },
  {
    name: 'Riz cantonais',
    emoji: '🍚',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'riz', foodName: 'Riz', quantity: 300, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 100, unit: 'g' },
      { foodId: 'surgele-petits-pois', foodName: 'Petits pois surgelés', quantity: 100, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 40, unit: 'ml' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Cuire le riz puis laisser refroidir (idéalement la veille).',
      'Faire revenir les lardons dans l\'huile.',
      'Ajouter le riz froid, mélanger à feu vif.',
      'Pousser le riz sur le côté, brouiller les œufs battus.',
      'Mélanger tout avec la sauce soja et les petits pois.',
    ],
  },

  // ─── DESSERTS ────────────────────────────────────────────
  {
    name: 'Mousse au chocolat',
    emoji: '🍫',
    category: 'Desserts',
    servings: 4,
    prepTime: 20,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'chocolat-noir', foodName: 'Chocolat noir', quantity: 200, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Faire fondre le chocolat avec le beurre au bain-marie.',
      'Séparer les blancs des jaunes d\'œufs.',
      'Incorporer les jaunes et le sucre au chocolat fondu.',
      'Monter les blancs en neige ferme.',
      'Incorporer délicatement les blancs en 3 fois.',
      'Réfrigérer au moins 2h avant de servir.',
    ],
  },
  {
    name: 'Crêpes',
    emoji: '🥞',
    category: 'Desserts',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'farine', foodName: 'Farine', quantity: 250, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'lait', foodName: 'Lait', quantity: 500, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Mélanger la farine, les œufs et le sucre.',
      'Ajouter le lait progressivement pour éviter les grumeaux.',
      'Incorporer le beurre fondu et la vanille.',
      'Laisser reposer 30 min, puis cuire les crêpes.',
    ],
  },
  {
    name: 'Tarte aux pommes',
    emoji: '🥧',
    category: 'Desserts',
    servings: 6,
    prepTime: 20,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'pate-brisee', foodName: 'Pâte brisée', quantity: 1, unit: 'unité' },
      { foodId: 'pomme', foodName: 'Pomme', quantity: 4, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 60, unit: 'g' },
      { foodId: 'cannelle', foodName: 'Cannelle', quantity: 3, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans le moule.',
      'Éplucher et couper les pommes en lamelles.',
      'Disposer les pommes, saupoudrer de sucre et cannelle.',
      'Parsemer de noisettes de beurre, cuire 35 min.',
    ],
  },
  {
    name: 'Tiramisu classique',
    emoji: '☕',
    category: 'Desserts',
    servings: 6,
    prepTime: 30,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'mascarpone', foodName: 'Mascarpone', quantity: 500, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
      { foodId: 'poudre-cacao', foodName: 'Poudre de cacao', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Séparer les blancs des jaunes. Battre jaunes + sucre jusqu\'à blanchiment.',
      'Incorporer le mascarpone aux jaunes.',
      'Monter les blancs en neige, les incorporer délicatement.',
      'Tremper les biscuits dans le café refroidi.',
      'Alterner couches de biscuits et crème, terminer par de la crème.',
      'Saupoudrer de cacao, réfrigérer 4h minimum.',
    ],
  },

  // ─── SNACKS ──────────────────────────────────────────────
  {
    name: 'Pain perdu',
    emoji: '🍞',
    category: 'Snacks',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'pain-de-mie', foodName: 'Pain de mie', quantity: 4, unit: 'tranche' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 3, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Battre les œufs avec le lait, le sucre et la vanille.',
      'Tremper les tranches de pain dans le mélange.',
      'Faire dorer dans le beurre 2-3 min de chaque côté.',
      'Servir chaud avec de la confiture ou du miel.',
    ],
  },
  {
    name: 'Soupe de lentilles au cumin',
    emoji: '🍲',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'lentilles', foodName: 'Lentilles', quantity: 300, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 2, unit: 'unité' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'curcuma', foodName: 'Curcuma', quantity: 3, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Faire revenir oignon, ail et carottes avec les épices.',
      'Ajouter les lentilles rincées et le bouillon cube.',
      'Couvrir d\'eau froide, porter à ébullition.',
      'Cuire 25 min à feu moyen, mixer partiellement.',
    ],
  },
];
