import { Recipe } from './types';

export const DEFAULT_RECIPES: Omit<Recipe, 'id'>[] = [
  // ─── APÉRO ───────────────────────────────────────────────
  {
    name: 'Bruschetta tomates basilic',
    emoji: '🍞',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 1, unit: 'unité' },
      { foodId: 'basilic', foodName: 'Basilic', quantity: 5, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Faire griller les tranches de pain.',
      'Frotter chaque tranche avec une gousse d\'ail.',
      'Couper les tomates en dés, assaisonner avec sel, poivre et basilic.',
      'Disposer les tomates sur le pain, arroser d\'huile d\'olive.',
    ],
  },
  {
    name: 'Guacamole maison',
    emoji: '🥑',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'tomate', foodName: 'Tomate', quantity: 1, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'coriandre', foodName: 'Coriandre', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Écraser les avocats à la fourchette.',
      'Ajouter la tomate coupée en dés, l\'oignon ciselé.',
      'Presser le citron, ajouter la coriandre et le sel.',
      'Mélanger et servir immédiatement.',
    ],
  },
  {
    name: 'Houmous express',
    emoji: '🫘',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'pois-chiches', foodName: 'Pois chiches', quantity: 400, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 40, unit: 'ml' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 3, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Égoutter et rincer les pois chiches.',
      'Mixer avec l\'ail, le jus de citron, l\'huile et le cumin.',
      'Saler, mixer jusqu\'à consistance crémeuse.',
      'Servir avec un filet d\'huile d\'olive.',
    ],
  },

  // ─── ENTRÉES ─────────────────────────────────────────────
  {
    name: 'Velouté de carottes au cumin',
    emoji: '🥕',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'carotte', foodName: 'Carotte', quantity: 6, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 100, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon émincé dans le beurre.',
      'Ajouter les carottes en rondelles et le cumin.',
      'Couvrir d\'eau avec le bouillon cube, cuire 20 min.',
      'Mixer finement, incorporer la crème fraîche.',
    ],
  },
  {
    name: 'Salade chèvre chaud & lardons',
    emoji: '🥗',
    category: 'Entrées',
    servings: 2,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'salade', foodName: 'Salade verte', quantity: 1, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 150, unit: 'g' },
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'vinaigre', foodName: 'Vinaigre', quantity: 20, unit: 'ml' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Faire revenir les lardons à la poêle.',
      'Poser le fromage de chèvre sur les tranches de pain et passer au gril.',
      'Préparer la vinaigrette moutarde/vinaigre/huile.',
      'Dresser la salade, ajouter les lardons, les toasts de chèvre chaud.',
    ],
  },

  // ─── PLATS ───────────────────────────────────────────────
  {
    name: 'Spaghetti bolognaise',
    emoji: '🍝',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 400, unit: 'g' },
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 400, unit: 'g' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 30, unit: 'g' },
      { foodId: 'herbes-provence', foodName: 'Herbes de Provence', quantity: 5, unit: 'g' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon et l\'ail émincés dans l\'huile d\'olive.',
      'Ajouter le bœuf haché, faire brunir.',
      'Incorporer les tomates concassées et le concentré, herbes, sel, poivre.',
      'Laisser mijoter 30 min à feu doux.',
      'Cuire les pâtes al dente, servir avec la sauce et le parmesan.',
    ],
  },
  {
    name: 'Curry de poulet au lait de coco',
    emoji: '🍛',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'blanc-poulet', foodName: 'Blanc de poulet', quantity: 600, unit: 'g' },
      { foodId: 'lait-coco', foodName: 'Lait de coco', quantity: 400, unit: 'ml' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'curry', foodName: 'Curry', quantity: 15, unit: 'g' },
      { foodId: 'riz-basmati', foodName: 'Riz basmati', quantity: 300, unit: 'g' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Faire revenir oignon et ail dans l\'huile.',
      'Ajouter le poulet coupé en dés, faire dorer.',
      'Saupoudrer de curry, mélanger 1 min.',
      'Verser le lait de coco, laisser mijoter 20 min.',
      'Servir avec le riz basmati cuit.',
    ],
  },
  {
    name: 'Quiche lorraine',
    emoji: '🥧',
    category: 'Plats',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'pate-brisee', foodName: 'Pâte brisée', quantity: 1, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 200, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
      { foodId: 'muscade', foodName: 'Noix de muscade', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans un moule, piquer le fond.',
      'Faire revenir les lardons, les disposer sur la pâte.',
      'Battre les œufs avec la crème et le lait, sel, muscade.',
      'Verser l\'appareil, saupoudrer de fromage râpé.',
      'Cuire 35 min jusqu\'à ce que la quiche soit dorée.',
    ],
  },
  {
    name: 'Ratatouille provençale',
    emoji: '🫕',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'aubergine', foodName: 'Aubergine', quantity: 1, unit: 'unité' },
      { foodId: 'courgette', foodName: 'Courgette', quantity: 2, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 3, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'herbes-provence', foodName: 'Herbes de Provence', quantity: 8, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 50, unit: 'ml' },
    ],
    instructions: [
      'Couper tous les légumes en dés.',
      'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
      'Ajouter les légumes par ordre de dureté (poivron, aubergine, courgette, tomate).',
      'Assaisonner avec les herbes de Provence, sel, poivre.',
      'Mijoter à couvert 30 min, puis 15 min à découvert.',
    ],
  },
  {
    name: 'Saumon à la crème et aneth',
    emoji: '🐟',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'saumon', foodName: 'Saumon', quantity: 400, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 150, unit: 'ml' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Assaisonner le saumon de sel, poivre et jus de citron.',
      'Faire cuire à la poêle dans le beurre, 4 min par côté.',
      'Réserver le saumon, déglacer avec la crème fraîche.',
      'Laisser réduire 2 min, ajouter le persil.',
      'Napper le saumon de sauce à la crème.',
    ],
  },
  {
    name: 'Omelette aux champignons',
    emoji: '🍳',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 150, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Faire revenir les champignons émincés dans le beurre.',
      'Battre les œufs avec sel, poivre et persil.',
      'Verser les œufs sur les champignons en poêle chaude.',
      'Plier l\'omelette dès que les bords sont pris.',
    ],
  },
  {
    name: 'Poulet rôti aux herbes',
    emoji: '🍗',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 70,
    isDefault: true,
    ingredients: [
      { foodId: 'poulet-entier', foodName: 'Poulet entier', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 50, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 4, unit: 'unité' },
      { foodId: 'thym', foodName: 'Thym', quantity: 5, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
      { foodId: 'sel', foodName: 'Sel', quantity: 5, unit: 'g' },
      { foodId: 'huile-olive', foodName: "Huile d'olive", quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Préchauffer le four à 200°C.',
      'Badigeonner le poulet de beurre mou, ail, thym, sel.',
      'Glisser les gousses d\'ail et le laurier dans la cavité.',
      'Rôtir 1h10 en arrosant régulièrement du jus de cuisson.',
    ],
  },
  {
    name: 'Riz cantonais',
    emoji: '🍚',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'riz', foodName: 'Riz', quantity: 300, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 100, unit: 'g' },
      { foodId: 'surgele-petits-pois', foodName: 'Petits pois surgelés', quantity: 100, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 40, unit: 'ml' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Cuire le riz puis laisser refroidir (idéalement la veille).',
      'Faire revenir les lardons dans l\'huile.',
      'Ajouter le riz froid, mélanger à feu vif.',
      'Pousser le riz sur le côté, brouiller les œufs battus.',
      'Mélanger tout avec la sauce soja et les petits pois.',
    ],
  },

  // ─── DESSERTS ────────────────────────────────────────────
  {
    name: 'Mousse au chocolat',
    emoji: '🍫',
    category: 'Desserts',
    servings: 4,
    prepTime: 20,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'chocolat-noir', foodName: 'Chocolat noir', quantity: 200, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Faire fondre le chocolat avec le beurre au bain-marie.',
      'Séparer les blancs des jaunes d\'œufs.',
      'Incorporer les jaunes et le sucre au chocolat fondu.',
      'Monter les blancs en neige ferme.',
      'Incorporer délicatement les blancs en 3 fois.',
      'Réfrigérer au moins 2h avant de servir.',
    ],
  },
  {
    name: 'Crêpes',
    emoji: '🥞',
    category: 'Desserts',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'farine', foodName: 'Farine', quantity: 250, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'lait', foodName: 'Lait', quantity: 500, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Mélanger la farine, les œufs et le sucre.',
      'Ajouter le lait progressivement pour éviter les grumeaux.',
      'Incorporer le beurre fondu et la vanille.',
      'Laisser reposer 30 min, puis cuire les crêpes.',
    ],
  },
  {
    name: 'Tarte aux pommes',
    emoji: '🥧',
    category: 'Desserts',
    servings: 6,
    prepTime: 20,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'pate-brisee', foodName: 'Pâte brisée', quantity: 1, unit: 'unité' },
      { foodId: 'pomme', foodName: 'Pomme', quantity: 4, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 60, unit: 'g' },
      { foodId: 'cannelle', foodName: 'Cannelle', quantity: 3, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans le moule.',
      'Éplucher et couper les pommes en lamelles.',
      'Disposer les pommes, saupoudrer de sucre et cannelle.',
      'Parsemer de noisettes de beurre, cuire 35 min.',
    ],
  },
  {
    name: 'Tiramisu classique',
    emoji: '☕',
    category: 'Desserts',
    servings: 6,
    prepTime: 30,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'mascarpone', foodName: 'Mascarpone', quantity: 500, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
      { foodId: 'poudre-cacao', foodName: 'Poudre de cacao', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Séparer les blancs des jaunes. Battre jaunes + sucre jusqu\'à blanchiment.',
      'Incorporer le mascarpone aux jaunes.',
      'Monter les blancs en neige, les incorporer délicatement.',
      'Tremper les biscuits dans le café refroidi.',
      'Alterner couches de biscuits et crème, terminer par de la crème.',
      'Saupoudrer de cacao, réfrigérer 4h minimum.',
    ],
  },

  // ─── APÉRO (suite) ───────────────────────────────────────
  {
    name: 'Gougères au fromage',
    emoji: '🧀',
    category: 'Apéro',
    servings: 6,
    prepTime: 15,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'farine', foodName: 'Farine', quantity: 120, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 80, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 100, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Porter à ébullition 150 ml d\'eau avec le beurre et le sel.',
      'Hors du feu, incorporer la farine d\'un coup, remuer vigoureusement.',
      'Ajouter les œufs un à un puis le fromage râpé.',
      'Former des petites boules sur une plaque, cuire 25 min à 200°C.',
    ],
  },
  {
    name: 'Tapenade d\'olives noires',
    emoji: '🫒',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'olives', foodName: 'Olives', quantity: 200, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 1, unit: 'unité' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 50, unit: 'ml' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'pain', foodName: 'Pain', quantity: 8, unit: 'tranche' },
    ],
    instructions: [
      'Dénoyauter les olives si nécessaire.',
      'Mixer olives, ail, jus de citron et huile d\'olive.',
      'Ajuster la texture (lisse ou rustique selon goût).',
      'Servir sur des toasts grillés.',
    ],
  },
  {
    name: 'Tomates cerises mozzarella',
    emoji: '🍅',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'tomate-cerise', foodName: 'Tomates cerises', quantity: 250, unit: 'g' },
      { foodId: 'mozzarella', foodName: 'Mozzarella', quantity: 1, unit: 'unité' },
      { foodId: 'basilic', foodName: 'Basilic', quantity: 10, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Couper les tomates cerises en deux, la mozzarella en dés.',
      'Disposer sur un plat, intercaler le basilic.',
      'Arroser d\'huile d\'olive, saler et poivrer.',
      'Servir aussitôt.',
    ],
  },
  {
    name: 'Rillettes de thon maison',
    emoji: '🐟',
    category: 'Apéro',
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'thon-boite', foodName: 'Thon en boîte', quantity: 2, unit: 'unité' },
      { foodId: 'fromage-blanc', foodName: 'Fromage blanc', quantity: 100, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 15, unit: 'g' },
      { foodId: 'cornichons', foodName: 'Cornichons', quantity: 4, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'pain', foodName: 'Pain', quantity: 8, unit: 'tranche' },
    ],
    instructions: [
      'Égoutter le thon et l\'émietter à la fourchette.',
      'Mélanger avec le fromage blanc, la moutarde et le jus de citron.',
      'Ajouter les cornichons ciselés, poivrer.',
      'Servir frais sur des toasts.',
    ],
  },
  {
    name: 'Œufs mimosa',
    emoji: '🥚',
    category: 'Apéro',
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 6, unit: 'unité' },
      { foodId: 'mayonnaise', foodName: 'Mayonnaise', quantity: 60, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Cuire les œufs durs 10 min, refroidir et écaler.',
      'Couper en deux, retirer les jaunes.',
      'Écraser les jaunes avec mayonnaise, moutarde, sel et poivre.',
      'Remplir les blancs du mélange, décorer de persil.',
    ],
  },

  // ─── ENTRÉES (suite) ─────────────────────────────────────
  {
    name: 'Soupe à l\'oignon gratinée',
    emoji: '🧅',
    category: 'Entrées',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'oignon', foodName: 'Oignon', quantity: 6, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 100, unit: 'g' },
      { foodId: 'thym', foodName: 'Thym', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Faire fondre et caraméliser les oignons émincés dans le beurre 30 min.',
      'Ajouter le bouillon cube et 1,5 L d\'eau chaude, thym, laisser mijoter 15 min.',
      'Verser dans des bols, poser une tranche de pain dessus.',
      'Couvrir de fromage râpé et passer au gril 5 min jusqu\'à gratinage.',
    ],
  },
  {
    name: 'Salade niçoise',
    emoji: '🥗',
    category: 'Entrées',
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'salade', foodName: 'Salade verte', quantity: 1, unit: 'unité' },
      { foodId: 'thon-boite', foodName: 'Thon en boîte', quantity: 1, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 2, unit: 'unité' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'olives', foodName: 'Olives', quantity: 50, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
      { foodId: 'vinaigre', foodName: 'Vinaigre', quantity: 15, unit: 'ml' },
    ],
    instructions: [
      'Cuire les œufs durs 10 min, les couper en quartiers.',
      'Dresser la salade, ajouter tomates, thon émietté, olives et œufs.',
      'Assaisonner d\'huile d\'olive, vinaigre, sel et poivre.',
    ],
  },
  {
    name: 'Gaspacho andalou',
    emoji: '🍅',
    category: 'Entrées',
    servings: 4,
    prepTime: 15,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'tomate', foodName: 'Tomate', quantity: 6, unit: 'unité' },
      { foodId: 'concombre', foodName: 'Concombre', quantity: 1, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 1, unit: 'unité' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 40, unit: 'ml' },
      { foodId: 'vinaigre', foodName: 'Vinaigre', quantity: 20, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Éplucher et épépiner tomates, concombre et poivron.',
      'Mixer tous les légumes avec l\'ail, l\'huile et le vinaigre.',
      'Saler, poivrer, filtrer si nécessaire.',
      'Réfrigérer 2h et servir très frais.',
    ],
  },
  {
    name: 'Velouté de champignons',
    emoji: '🍄',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'champignons', foodName: 'Champignons', quantity: 400, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 100, unit: 'ml' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon et les champignons dans le beurre.',
      'Ajouter le bouillon cube et 800 ml d\'eau, cuire 15 min.',
      'Mixer finement, incorporer la crème fraîche.',
      'Servir chaud avec le persil ciselé.',
    ],
  },
  {
    name: 'Salade de lentilles vinaigrette',
    emoji: '🫘',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'lentilles', foodName: 'Lentilles', quantity: 300, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 1, unit: 'unité' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 15, unit: 'g' },
      { foodId: 'vinaigre', foodName: 'Vinaigre', quantity: 20, unit: 'ml' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Cuire les lentilles avec carotte et oignon 25 min dans l\'eau salée.',
      'Égoutter et laisser tiédir.',
      'Préparer la vinaigrette moutarde/vinaigre/huile.',
      'Mélanger, parsemer de persil et servir tiède.',
    ],
  },
  {
    name: 'Velouté de poireaux',
    emoji: '🥬',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'poireau', foodName: 'Poireau', quantity: 3, unit: 'unité' },
      { foodId: 'pomme-de-terre', foodName: 'Pomme de terre', quantity: 2, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 100, unit: 'ml' },
    ],
    instructions: [
      'Émincer les poireaux, les faire fondre dans le beurre 5 min.',
      'Ajouter les pommes de terre coupées en dés et le bouillon.',
      'Couvrir d\'eau, cuire 20 min à feu doux.',
      'Mixer et incorporer la crème fraîche avant de servir.',
    ],
  },

  // ─── PLATS - Cuisine française ───────────────────────────
  {
    name: 'Bœuf bourguignon',
    emoji: '🥩',
    category: 'Plats',
    servings: 6,
    prepTime: 30,
    cookTime: 150,
    isDefault: true,
    ingredients: [
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 800, unit: 'g' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 150, unit: 'g' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 200, unit: 'g' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 3, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 30, unit: 'g' },
      { foodId: 'thym', foodName: 'Thym', quantity: 3, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
    ],
    instructions: [
      'Faire revenir les lardons, réserver. Faire dorer le bœuf en morceaux.',
      'Ajouter oignons, carottes, concentré de tomate, thym et laurier.',
      'Couvrir de bouillon, laisser mijoter 2h à feu très doux.',
      'Ajouter les champignons 20 min avant la fin.',
    ],
  },
  {
    name: 'Gratin dauphinois',
    emoji: '🥔',
    category: 'Plats',
    servings: 6,
    prepTime: 20,
    cookTime: 60,
    isDefault: true,
    ingredients: [
      { foodId: 'pomme-de-terre', foodName: 'Pomme de terre', quantity: 8, unit: 'unité' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 300, unit: 'ml' },
      { foodId: 'lait', foodName: 'Lait', quantity: 200, unit: 'ml' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'muscade', foodName: 'Noix de muscade', quantity: 2, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Préchauffer le four à 180°C. Frotter le plat avec l\'ail.',
      'Éplucher et couper les pommes de terre en fines rondelles.',
      'Mélanger crème, lait, muscade, sel et poivre.',
      'Alterner couches de pommes de terre et crème, terminer par le fromage. Cuire 1h.',
    ],
  },
  {
    name: 'Blanquette de veau',
    emoji: '🥩',
    category: 'Plats',
    servings: 6,
    prepTime: 20,
    cookTime: 90,
    isDefault: true,
    ingredients: [
      { foodId: 'escalope-veau', foodName: 'Escalope de veau', quantity: 6, unit: 'unité' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 3, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 200, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
    ],
    instructions: [
      'Faire blanchir le veau 5 min dans l\'eau bouillante, égoutter.',
      'Cuire le veau avec carottes, oignons, bouillon, laurier 1h à feu doux.',
      'Faire revenir les champignons dans le beurre, les ajouter.',
      'Lier avec la crème fraîche et un peu de jus de citron avant de servir.',
    ],
  },
  {
    name: 'Hachis parmentier',
    emoji: '🥔',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 40,
    isDefault: true,
    ingredients: [
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 500, unit: 'g' },
      { foodId: 'pomme-de-terre', foodName: 'Pomme de terre', quantity: 8, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 50, unit: 'g' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Cuire les pommes de terre, les écraser en purée avec beurre et lait.',
      'Faire revenir l\'oignon et le bœuf haché avec le concentré de tomate.',
      'Disposer la viande dans un plat, couvrir de purée.',
      'Parsemer de fromage râpé et gratiner 20 min à 200°C.',
    ],
  },
  {
    name: 'Moules marinières',
    emoji: '🦪',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'moules', foodName: 'Moules', quantity: 2, unit: 'kg' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 10, unit: 'g' },
      { foodId: 'thym', foodName: 'Thym', quantity: 3, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
    ],
    instructions: [
      'Nettoyer et gratter les moules, jeter celles qui sont ouvertes.',
      'Faire suer oignon et ail dans le beurre.',
      'Ajouter thym, laurier et les moules, couvrir et cuire 5 min à feu vif.',
      'Secouer régulièrement, servir dès que les moules sont ouvertes avec le persil.',
    ],
  },
  {
    name: 'Coq au vin',
    emoji: '🍗',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 60,
    isDefault: true,
    ingredients: [
      { foodId: 'cuisse-poulet', foodName: 'Cuisse de poulet', quantity: 4, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 150, unit: 'g' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 200, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 20, unit: 'g' },
      { foodId: 'thym', foodName: 'Thym', quantity: 3, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
    ],
    instructions: [
      'Faire dorer les cuisses de poulet sur toutes les faces, réserver.',
      'Faire revenir lardons, oignons, ail et champignons.',
      'Remettre le poulet, ajouter le bouillon et les aromates.',
      'Mijoter 45 min à couvert à feu doux.',
    ],
  },
  {
    name: 'Tartiflette savoyarde',
    emoji: '🥔',
    category: 'Plats',
    servings: 6,
    prepTime: 20,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'pomme-de-terre', foodName: 'Pomme de terre', quantity: 8, unit: 'unité' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 200, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'camembert', foodName: 'Camembert', quantity: 1, unit: 'unité' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 150, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Cuire les pommes de terre à l\'eau, les trancher en rondelles.',
      'Faire revenir les lardons et les oignons.',
      'Alterner pommes de terre et lardons dans un plat, verser la crème.',
      'Poser le camembert coupé en deux (croûte vers le haut), cuire 25 min à 200°C.',
    ],
  },
  {
    name: 'Sole meunière',
    emoji: '🐡',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'sole', foodName: 'Sole', quantity: 2, unit: 'unité' },
      { foodId: 'farine', foodName: 'Farine', quantity: 50, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 60, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Fariner les soles, secouer l\'excédent.',
      'Cuire dans le beurre mousseux 3 min par côté, saler.',
      'Réserver les soles, faire noisetter le reste du beurre.',
      'Napper du beurre noisette, presser le citron, parsemer de persil.',
    ],
  },
  {
    name: 'Croque-monsieur',
    emoji: '🧀',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'pain-de-mie', foodName: 'Pain de mie', quantity: 4, unit: 'tranche' },
      { foodId: 'jambon', foodName: 'Jambon blanc', quantity: 2, unit: 'tranche' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Tartiner de moutarde 2 tranches de pain.',
      'Poser le jambon et la moitié du fromage, refermer.',
      'Beurrer l\'extérieur et cuire à la poêle 3 min par côté.',
      'Couvrir du reste de fromage et passer 2 min au gril.',
    ],
  },
  {
    name: 'Lapin à la moutarde',
    emoji: '🐇',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 60,
    isDefault: true,
    ingredients: [
      { foodId: 'cuisse-poulet', foodName: 'Cuisse de poulet', quantity: 4, unit: 'unité' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 80, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'thym', foodName: 'Thym', quantity: 3, unit: 'g' },
      { foodId: 'laurier', foodName: 'Laurier', quantity: 2, unit: 'unité' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Enduire généreusement le poulet de moutarde.',
      'Faire dorer les morceaux dans l\'huile d\'olive.',
      'Ajouter l\'oignon, thym, laurier et 200 ml d\'eau, couvrir 40 min.',
      'Incorporer la crème fraîche et cuire encore 10 min à découvert.',
    ],
  },
  {
    name: 'Brandade de morue',
    emoji: '🐟',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'cabillaud', foodName: 'Cabillaud', quantity: 500, unit: 'g' },
      { foodId: 'pomme-de-terre', foodName: 'Pomme de terre', quantity: 4, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 80, unit: 'ml' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Cuire le cabillaud dans le lait 10 min, effeuiller.',
      'Cuire les pommes de terre à l\'eau, écraser grossièrement.',
      'Mélanger poisson, purée, ail et huile d\'olive progressivement.',
      'Gratiner 15 min au four à 200°C.',
    ],
  },

  // ─── PLATS - Cuisine italienne ────────────────────────────
  {
    name: 'Pâtes carbonara',
    emoji: '🍝',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 400, unit: 'g' },
      { foodId: 'lardons', foodName: 'Lardons', quantity: 150, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 80, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
      { foodId: 'poivre', foodName: 'Poivre', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Cuire les pâtes al dente, réserver 1 louche d\'eau de cuisson.',
      'Faire revenir les lardons à sec jusqu\'à dorure.',
      'Battre les œufs avec le parmesan et beaucoup de poivre.',
      'Hors du feu, mélanger pâtes égouttées, lardons et œufs en ajoutant l\'eau de cuisson pour lier.',
    ],
  },
  {
    name: 'Risotto aux champignons',
    emoji: '🍄',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'riz', foodName: 'Riz', quantity: 320, unit: 'g' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 300, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 60, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Préparer 1,2 L de bouillon chaud avec les cubes.',
      'Faire revenir oignon et champignons dans l\'huile, ajouter le riz et nacrer 2 min.',
      'Ajouter le bouillon louche par louche en remuant constamment sur 20 min.',
      'Hors du feu, incorporer le beurre et le parmesan (mantecatura).',
    ],
  },
  {
    name: 'Lasagnes bolognaise',
    emoji: '🍝',
    category: 'Plats',
    servings: 6,
    prepTime: 30,
    cookTime: 50,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 250, unit: 'g' },
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 500, unit: 'g' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'farine', foodName: 'Farine', quantity: 40, unit: 'g' },
      { foodId: 'lait', foodName: 'Lait', quantity: 500, unit: 'ml' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 100, unit: 'g' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Préparer la bolognaise : faire revenir oignon, bœuf et tomates concassées 20 min.',
      'Préparer la béchamel : faire fondre beurre, ajouter farine puis lait progressivement.',
      'Alterner couches de pâtes, bolognaise et béchamel dans un plat.',
      'Terminer par la béchamel, fromage et parmesan, cuire 40 min à 180°C.',
    ],
  },
  {
    name: 'Penne à l\'arrabbiata',
    emoji: '🍝',
    category: 'Plats',
    servings: 4,
    prepTime: 5,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 400, unit: 'g' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 4, unit: 'unité' },
      { foodId: 'piment', foodName: 'Piment', quantity: 3, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 40, unit: 'ml' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 40, unit: 'g' },
      { foodId: 'basilic', foodName: 'Basilic', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'ail haché et le piment dans l\'huile d\'olive.',
      'Ajouter les tomates concassées, cuire 15 min à feu vif.',
      'Cuire les pâtes al dente, mélanger avec la sauce.',
      'Servir avec parmesan et basilic frais.',
    ],
  },
  {
    name: 'Risotto au parmesan',
    emoji: '🧀',
    category: 'Plats',
    servings: 4,
    prepTime: 5,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'riz', foodName: 'Riz', quantity: 320, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 60, unit: 'g' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 100, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Faire revenir l\'oignon dans la moitié du beurre, nacrer le riz 2 min.',
      'Ajouter le bouillon chaud louche par louche, remuer 20 min.',
      'Hors du feu, mantecare avec le reste du beurre et le parmesan.',
      'Laisser reposer 2 min avant de servir.',
    ],
  },

  // ─── PLATS - Cuisine asiatique ────────────────────────────
  {
    name: 'Bœuf wok aux brocolis',
    emoji: '🥦',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'steak-boeuf', foodName: 'Steak de bœuf', quantity: 4, unit: 'unité' },
      { foodId: 'brocoli', foodName: 'Brocoli', quantity: 1, unit: 'unité' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 50, unit: 'ml' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 30, unit: 'ml' },
      { foodId: 'riz', foodName: 'Riz', quantity: 300, unit: 'g' },
      { foodId: 'miel', foodName: 'Miel', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Couper le bœuf en lamelles, mariner avec sauce soja et miel.',
      'Faire cuire le riz. Blanchir le brocoli 3 min.',
      'Saisir le bœuf à feu très vif dans le wok huilé, ajouter l\'ail.',
      'Ajouter le brocoli et la marinade, remuer 2 min. Servir sur le riz.',
    ],
  },
  {
    name: 'Crevettes sautées au soja et miel',
    emoji: '🦐',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'crevettes', foodName: 'Crevettes', quantity: 400, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 40, unit: 'ml' },
      { foodId: 'miel', foodName: 'Miel', quantity: 20, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'riz-basmati', foodName: 'Riz basmati', quantity: 300, unit: 'g' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Cuire le riz basmati.',
      'Mélanger sauce soja, miel et ail haché.',
      'Saisir les crevettes 2 min dans l\'huile bien chaude.',
      'Verser la sauce, enrober 1 min. Servir sur le riz.',
    ],
  },
  {
    name: 'Soupe miso aux légumes',
    emoji: '🍜',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 150, unit: 'g' },
      { foodId: 'epinards', foodName: 'Épinards', quantity: 100, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 40, unit: 'ml' },
      { foodId: 'ail', foodName: 'Ail', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Porter à ébullition 1,5 L de bouillon.',
      'Ajouter champignons émincés et laisser cuire 5 min.',
      'Ajouter le tofu coupé en dés, les épinards et la sauce soja.',
      'Servir chaud avec éventuellement des nouilles.',
    ],
  },
  {
    name: 'Poulet teriyaki',
    emoji: '🍗',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'blanc-poulet', foodName: 'Blanc de poulet', quantity: 600, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 60, unit: 'ml' },
      { foodId: 'miel', foodName: 'Miel', quantity: 30, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'riz', foodName: 'Riz', quantity: 300, unit: 'g' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 20, unit: 'ml' },
    ],
    instructions: [
      'Mélanger sauce soja, miel et ail → marinade teriyaki.',
      'Faire mariner le poulet 30 min.',
      'Cuire le poulet à la poêle 6 min par côté en versant la marinade.',
      'Réduire la sauce 2 min jusqu\'à glaçage. Servir sur le riz cuit.',
    ],
  },
  {
    name: 'Porc sauté aux légumes wok',
    emoji: '🥢',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    isDefault: true,
    ingredients: [
      { foodId: 'cote-porc', foodName: 'Côte de porc', quantity: 4, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'courgette', foodName: 'Courgette', quantity: 1, unit: 'unité' },
      { foodId: 'champignons', foodName: 'Champignons', quantity: 150, unit: 'g' },
      { foodId: 'sauce-soja', foodName: 'Sauce soja', quantity: 40, unit: 'ml' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'riz', foodName: 'Riz', quantity: 300, unit: 'g' },
    ],
    instructions: [
      'Couper la viande et les légumes en lanières.',
      'Saisir le porc à feu vif dans le wok huilé 5 min, réserver.',
      'Faire sauter les légumes avec l\'ail 5 min.',
      'Remettre le porc, ajouter la sauce soja, mélanger 2 min. Servir avec le riz.',
    ],
  },

  // ─── PLATS - Cuisine du monde ─────────────────────────────
  {
    name: 'Tajine de poulet aux olives',
    emoji: '🍲',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 60,
    isDefault: true,
    ingredients: [
      { foodId: 'cuisse-poulet', foodName: 'Cuisse de poulet', quantity: 4, unit: 'unité' },
      { foodId: 'olives', foodName: 'Olives', quantity: 150, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 3, unit: 'unité' },
      { foodId: 'curcuma', foodName: 'Curcuma', quantity: 5, unit: 'g' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 40, unit: 'ml' },
      { foodId: 'coriandre', foodName: 'Coriandre', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Faire dorer les cuisses de poulet avec oignons et ail dans l\'huile.',
      'Ajouter les épices, le jus de citron et 200 ml d\'eau.',
      'Couvrir et mijoter 45 min à feu doux.',
      'Ajouter les olives 10 min avant la fin, garnir de coriandre.',
    ],
  },
  {
    name: 'Chili con carne',
    emoji: '🌶️',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    isDefault: true,
    ingredients: [
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 500, unit: 'g' },
      { foodId: 'haricots-blancs', foodName: 'Haricots blancs', quantity: 400, unit: 'g' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'piment', foodName: 'Piment', quantity: 5, unit: 'g' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'paprika', foodName: 'Paprika', quantity: 5, unit: 'g' },
      { foodId: 'concentre-tomate', foodName: 'Concentré de tomate', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Faire revenir oignon, poivron et bœuf haché.',
      'Ajouter épices, concentré de tomate et tomates concassées.',
      'Incorporer les haricots, laisser mijoter 30 min.',
      'Ajuster l\'assaisonnement. Servir avec du riz ou du pain.',
    ],
  },
  {
    name: 'Shakshuka',
    emoji: '🍳',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'tomates-concassees', foodName: 'Tomates concassées', quantity: 2, unit: 'unité' },
      { foodId: 'poivron-rouge', foodName: 'Poivron rouge', quantity: 1, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'paprika', foodName: 'Paprika', quantity: 5, unit: 'g' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 3, unit: 'g' },
      { foodId: 'piment', foodName: 'Piment', quantity: 2, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 30, unit: 'ml' },
    ],
    instructions: [
      'Faire revenir oignon, ail et poivron dans l\'huile.',
      'Ajouter épices, puis tomates concassées. Mijoter 10 min.',
      'Creuser des puits dans la sauce, casser les œufs dedans.',
      'Couvrir et cuire 8 min jusqu\'à ce que les blancs soient pris.',
    ],
  },
  {
    name: 'Dahl de lentilles corail',
    emoji: '🫘',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'lentilles', foodName: 'Lentilles', quantity: 300, unit: 'g' },
      { foodId: 'lait-coco', foodName: 'Lait de coco', quantity: 400, unit: 'ml' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 2, unit: 'unité' },
      { foodId: 'curry', foodName: 'Curry', quantity: 10, unit: 'g' },
      { foodId: 'curcuma', foodName: 'Curcuma', quantity: 5, unit: 'g' },
      { foodId: 'coriandre', foodName: 'Coriandre', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Faire revenir oignon et ail avec les épices.',
      'Ajouter les tomates, les lentilles rincées et le lait de coco.',
      'Couvrir de 200 ml d\'eau, cuire 20 min en remuant.',
      'Parsemer de coriandre fraîche. Servir avec du riz basmati.',
    ],
  },
  {
    name: 'Couscous au poulet',
    emoji: '🌾',
    category: 'Plats',
    servings: 4,
    prepTime: 20,
    cookTime: 50,
    isDefault: true,
    ingredients: [
      { foodId: 'cuisse-poulet', foodName: 'Cuisse de poulet', quantity: 4, unit: 'unité' },
      { foodId: 'semoule', foodName: 'Semoule', quantity: 300, unit: 'g' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 3, unit: 'unité' },
      { foodId: 'courgette', foodName: 'Courgette', quantity: 2, unit: 'unité' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 2, unit: 'unité' },
      { foodId: 'pois-chiches', foodName: 'Pois chiches', quantity: 200, unit: 'g' },
      { foodId: 'curcuma', foodName: 'Curcuma', quantity: 5, unit: 'g' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 2, unit: 'unité' },
    ],
    instructions: [
      'Faire dorer le poulet avec les oignons et les épices.',
      'Ajouter le bouillon, carottes et courgettes, mijoter 30 min.',
      'Ajouter les pois chiches et cuire encore 10 min.',
      'Préparer la semoule selon les instructions, servir avec le bouillon.',
    ],
  },

  // ─── PLATS - Rapides ──────────────────────────────────────
  {
    name: 'Pâtes au pesto maison',
    emoji: '🌿',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 400, unit: 'g' },
      { foodId: 'basilic', foodName: 'Basilic', quantity: 40, unit: 'g' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'parmesan', foodName: 'Parmesan', quantity: 60, unit: 'g' },
      { foodId: 'huile-olive', foodName: 'Huile d\'olive', quantity: 80, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Cuire les pâtes al dente.',
      'Mixer basilic, ail, parmesan et huile d\'olive jusqu\'à obtenir un pesto lisse.',
      'Mélanger les pâtes égouttées avec le pesto, ajouter un peu d\'eau de cuisson.',
      'Servir avec des copeaux de parmesan.',
    ],
  },
  {
    name: 'Steak haché frites au four',
    emoji: '🍔',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'boeuf-hache', foodName: 'Bœuf haché', quantity: 600, unit: 'g' },
      { foodId: 'surgele-frites', foodName: 'Frites surgelées', quantity: 600, unit: 'g' },
      { foodId: 'sel', foodName: 'Sel', quantity: 3, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 20, unit: 'g' },
      { foodId: 'ketchup', foodName: 'Ketchup', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Enfourner les frites selon les instructions (35 min à 200°C).',
      'Former 4 steak hachés, assaisonner de sel et poivre.',
      'Cuire les steaks à la poêle, 3 min par côté à feu vif.',
      'Servir avec frites, moutarde et ketchup.',
    ],
  },
  {
    name: 'Salade de pâtes thon maïs',
    emoji: '🥗',
    category: 'Plats',
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 300, unit: 'g' },
      { foodId: 'thon-boite', foodName: 'Thon en boîte', quantity: 2, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 2, unit: 'unité' },
      { foodId: 'concombre', foodName: 'Concombre', quantity: 1, unit: 'unité' },
      { foodId: 'mayonnaise', foodName: 'Mayonnaise', quantity: 60, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Cuire les pâtes, rincer à l\'eau froide.',
      'Égoutter le thon, couper tomates et concombre en dés.',
      'Préparer la sauce avec mayo, moutarde et jus de citron.',
      'Mélanger tout ensemble, réfrigérer avant de servir.',
    ],
  },
  {
    name: 'Œufs brouillés crémeux',
    emoji: '🍳',
    category: 'Plats',
    servings: 2,
    prepTime: 5,
    cookTime: 8,
    isDefault: true,
    ingredients: [
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 6, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 30, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 50, unit: 'ml' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
      { foodId: 'pain', foodName: 'Pain', quantity: 2, unit: 'tranche' },
    ],
    instructions: [
      'Battre les œufs avec sel et poivre.',
      'Cuire à feu très doux dans le beurre en remuant constamment.',
      'Hors du feu, incorporer la crème fraîche.',
      'Servir immédiatement sur le pain grillé.',
    ],
  },
  {
    name: 'Gratin de pâtes au jambon',
    emoji: '🍝',
    category: 'Plats',
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    isDefault: true,
    ingredients: [
      { foodId: 'pates', foodName: 'Pâtes', quantity: 350, unit: 'g' },
      { foodId: 'jambon', foodName: 'Jambon blanc', quantity: 4, unit: 'tranche' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 40, unit: 'g' },
      { foodId: 'farine', foodName: 'Farine', quantity: 40, unit: 'g' },
      { foodId: 'lait', foodName: 'Lait', quantity: 500, unit: 'ml' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 100, unit: 'g' },
      { foodId: 'muscade', foodName: 'Noix de muscade', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Cuire les pâtes al dente.',
      'Préparer la béchamel : beurre + farine + lait chaud + muscade.',
      'Mélanger pâtes, jambon coupé et béchamel dans un plat.',
      'Couvrir de fromage râpé et gratiner 20 min à 200°C.',
    ],
  },

  // ─── DESSERTS (suite) ─────────────────────────────────────
  {
    name: 'Fondant au chocolat',
    emoji: '🍫',
    category: 'Desserts',
    servings: 6,
    prepTime: 15,
    cookTime: 12,
    isDefault: true,
    ingredients: [
      { foodId: 'chocolat-noir', foodName: 'Chocolat noir', quantity: 200, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 120, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 4, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
      { foodId: 'farine', foodName: 'Farine', quantity: 40, unit: 'g' },
    ],
    instructions: [
      'Faire fondre chocolat et beurre au bain-marie.',
      'Battre œufs et sucre jusqu\'à blanchiment, incorporer le chocolat.',
      'Ajouter la farine, verser dans des moules beurrés.',
      'Cuire 12 min à 200°C, le cœur doit rester coulant.',
    ],
  },
  {
    name: 'Gâteau au yaourt',
    emoji: '🍰',
    category: 'Desserts',
    servings: 8,
    prepTime: 10,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'yaourt', foodName: 'Yaourt nature', quantity: 1, unit: 'unité' },
      { foodId: 'farine', foodName: 'Farine', quantity: 300, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 150, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'huile-tournesol', foodName: 'Huile de tournesol', quantity: 100, unit: 'ml' },
      { foodId: 'levure', foodName: 'Levure chimique', quantity: 10, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Mélanger yaourt, sucre, œufs et huile.',
      'Ajouter farine, levure et vanille, mélanger jusqu\'à homogénéité.',
      'Verser dans un moule beurré.',
      'Cuire 35 min à 180°C (vérifier avec un cure-dent).',
    ],
  },
  {
    name: 'Tarte tatin',
    emoji: '🍎',
    category: 'Desserts',
    servings: 6,
    prepTime: 20,
    cookTime: 40,
    isDefault: true,
    ingredients: [
      { foodId: 'pate-feuilletee', foodName: 'Pâte feuilletée', quantity: 1, unit: 'unité' },
      { foodId: 'pomme', foodName: 'Pomme', quantity: 6, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 120, unit: 'g' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 60, unit: 'g' },
      { foodId: 'cannelle', foodName: 'Cannelle', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Faire un caramel avec sucre et beurre dans un moule allant au four.',
      'Éplucher et couper les pommes en quartiers, les disposer sur le caramel.',
      'Saupoudrer de cannelle, couvrir de pâte feuilletée en rentrant les bords.',
      'Cuire 35 min à 200°C, retourner immédiatement sur un plat.',
    ],
  },
  {
    name: 'Clafoutis aux fraises',
    emoji: '🍓',
    category: 'Desserts',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    isDefault: true,
    ingredients: [
      { foodId: 'fraises', foodName: 'Fraises', quantity: 400, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'farine', foodName: 'Farine', quantity: 80, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
      { foodId: 'lait', foodName: 'Lait', quantity: 300, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Préchauffer le four à 180°C, beurrer un plat.',
      'Disposer les fraises équeutées dans le plat.',
      'Battre œufs, sucre, farine, lait et vanille jusqu\'à consistance lisse.',
      'Verser l\'appareil sur les fraises, cuire 35 min.',
    ],
  },
  {
    name: 'Panna cotta vanille coulis framboises',
    emoji: '🫐',
    category: 'Desserts',
    servings: 4,
    prepTime: 15,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 400, unit: 'ml' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 60, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
      { foodId: 'framboises', foodName: 'Framboises', quantity: 200, unit: 'g' },
    ],
    instructions: [
      'Porter la crème, le lait, le sucre et la vanille à frémissement (sans bouillir).',
      'Incorporer 3 feuilles de gélatine préalablement ramollies dans l\'eau froide.',
      'Verser dans des ramequins, réfrigérer 4h minimum.',
      'Mixer les framboises avec un peu de sucre pour le coulis, servir sur la panna cotta.',
    ],
  },
  {
    name: 'Madeleine au citron',
    emoji: '🍋',
    category: 'Desserts',
    servings: 12,
    prepTime: 15,
    cookTime: 12,
    isDefault: true,
    ingredients: [
      { foodId: 'farine', foodName: 'Farine', quantity: 200, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 150, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 3, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 150, unit: 'g' },
      { foodId: 'levure', foodName: 'Levure chimique', quantity: 8, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Battre œufs et sucre jusqu\'à blanchiment, ajouter le zeste de citron.',
      'Incorporer farine et levure, puis le beurre fondu.',
      'Réfrigérer la pâte 30 min, remplir les moules à madeleines aux ¾.',
      'Cuire 12 min à 200°C jusqu\'à la bosse caractéristique.',
    ],
  },
  {
    name: 'Charlotte aux framboises',
    emoji: '🫐',
    category: 'Desserts',
    servings: 8,
    prepTime: 30,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'framboises', foodName: 'Framboises', quantity: 400, unit: 'g' },
      { foodId: 'mascarpone', foodName: 'Mascarpone', quantity: 250, unit: 'g' },
      { foodId: 'creme-fraiche', foodName: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Monter la crème fraîche en chantilly, l\'incorporer au mascarpone avec sucre et vanille.',
      'Tapisser un moule de film alimentaire.',
      'Alterner couches de framboises et mousse.',
      'Réfrigérer 4h minimum, démouler au service.',
    ],
  },
  {
    name: 'Compote de pommes maison',
    emoji: '🍎',
    category: 'Desserts',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    isDefault: true,
    ingredients: [
      { foodId: 'pomme', foodName: 'Pomme', quantity: 6, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 60, unit: 'g' },
      { foodId: 'cannelle', foodName: 'Cannelle', quantity: 2, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 3, unit: 'ml' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Éplucher et couper les pommes en morceaux.',
      'Cuire avec sucre, cannelle, vanille et jus de citron 20 min à couvert.',
      'Mixer partiellement ou laisser en morceaux selon les goûts.',
      'Servir chaud ou froid, nature ou avec une boule de glace.',
    ],
  },

  // ─── SNACKS ──────────────────────────────────────────────
  {
    name: 'Pain perdu',
    emoji: '🍞',
    category: 'Snacks',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'pain-de-mie', foodName: 'Pain de mie', quantity: 4, unit: 'tranche' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'lait', foodName: 'Lait', quantity: 100, unit: 'ml' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 3, unit: 'ml' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Battre les œufs avec le lait, le sucre et la vanille.',
      'Tremper les tranches de pain dans le mélange.',
      'Faire dorer dans le beurre 2-3 min de chaque côté.',
      'Servir chaud avec de la confiture ou du miel.',
    ],
  },
  {
    name: 'Soupe de lentilles au cumin',
    emoji: '🍲',
    category: 'Entrées',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    isDefault: true,
    ingredients: [
      { foodId: 'lentilles', foodName: 'Lentilles', quantity: 300, unit: 'g' },
      { foodId: 'oignon', foodName: 'Oignon', quantity: 1, unit: 'unité' },
      { foodId: 'ail', foodName: 'Ail', quantity: 2, unit: 'unité' },
      { foodId: 'carotte', foodName: 'Carotte', quantity: 2, unit: 'unité' },
      { foodId: 'cumin', foodName: 'Cumin', quantity: 5, unit: 'g' },
      { foodId: 'curcuma', foodName: 'Curcuma', quantity: 3, unit: 'g' },
      { foodId: 'bouillon-cube', foodName: 'Bouillon cube', quantity: 1, unit: 'unité' },
    ],
    instructions: [
      'Faire revenir oignon, ail et carottes avec les épices.',
      'Ajouter les lentilles rincées et le bouillon cube.',
      'Couvrir d\'eau froide, porter à ébullition.',
      'Cuire 25 min à feu moyen, mixer partiellement.',
    ],
  },
  {
    name: 'Tartines avocat œuf',
    emoji: '🥑',
    category: 'Snacks',
    servings: 2,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'pain', foodName: 'Pain', quantity: 2, unit: 'tranche' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'sel', foodName: 'Sel', quantity: 2, unit: 'g' },
      { foodId: 'piment', foodName: 'Piment', quantity: 1, unit: 'g' },
    ],
    instructions: [
      'Griller les tranches de pain.',
      'Cuire les œufs au plat ou pochés.',
      'Écraser la chair d\'avocat avec le jus de citron, sel et piment.',
      'Étaler sur le pain, poser l\'œuf dessus.',
    ],
  },
  {
    name: 'Wrap poulet crudités',
    emoji: '🌯',
    category: 'Snacks',
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'blanc-poulet', foodName: 'Blanc de poulet', quantity: 300, unit: 'g' },
      { foodId: 'pain-de-mie', foodName: 'Pain de mie', quantity: 2, unit: 'tranche' },
      { foodId: 'salade', foodName: 'Salade verte', quantity: 1, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 1, unit: 'unité' },
      { foodId: 'mayonnaise', foodName: 'Mayonnaise', quantity: 40, unit: 'g' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Cuire le poulet en lanières à la poêle, saler, poivrer.',
      'Mélanger mayonnaise et moutarde.',
      'Étaler la sauce sur les tortillas ou le pain.',
      'Ajouter poulet, salade et tomate, rouler serré.',
    ],
  },
  {
    name: 'Tartines sardines tomates',
    emoji: '🐟',
    category: 'Snacks',
    servings: 2,
    prepTime: 5,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'pain', foodName: 'Pain', quantity: 4, unit: 'tranche' },
      { foodId: 'sardines-boite', foodName: 'Sardines en boîte', quantity: 1, unit: 'unité' },
      { foodId: 'tomate', foodName: 'Tomate', quantity: 1, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'moutarde', foodName: 'Moutarde', quantity: 10, unit: 'g' },
      { foodId: 'persil', foodName: 'Persil', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Griller les tranches de pain.',
      'Écraser les sardines avec la moutarde et le jus de citron.',
      'Étaler sur le pain, garnir de tomate en tranches.',
      'Parsemer de persil frais.',
    ],
  },
  {
    name: 'Smoothie bowl fraises banane',
    emoji: '🍓',
    category: 'Snacks',
    servings: 1,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'fraises', foodName: 'Fraises', quantity: 200, unit: 'g' },
      { foodId: 'banane', foodName: 'Banane', quantity: 1, unit: 'unité' },
      { foodId: 'yaourt', foodName: 'Yaourt nature', quantity: 1, unit: 'unité' },
      { foodId: 'miel', foodName: 'Miel', quantity: 15, unit: 'g' },
      { foodId: 'flocons-avoine', foodName: 'Flocons d\'avoine', quantity: 30, unit: 'g' },
    ],
    instructions: [
      'Mixer fraises et banane congelées avec le yaourt jusqu\'à consistance épaisse.',
      'Verser dans un bol.',
      'Garnir de flocons d\'avoine et d\'un filet de miel.',
    ],
  },
  {
    name: 'Croque-madame',
    emoji: '🍳',
    category: 'Snacks',
    servings: 2,
    prepTime: 5,
    cookTime: 12,
    isDefault: true,
    ingredients: [
      { foodId: 'pain-de-mie', foodName: 'Pain de mie', quantity: 4, unit: 'tranche' },
      { foodId: 'jambon', foodName: 'Jambon blanc', quantity: 2, unit: 'tranche' },
      { foodId: 'fromage-rape', foodName: 'Fromage râpé', quantity: 80, unit: 'g' },
      { foodId: 'oeuf', foodName: 'Œuf', quantity: 2, unit: 'unité' },
      { foodId: 'beurre', foodName: 'Beurre', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Assembler et griller le croque-monsieur (jambon + fromage entre deux tranches).',
      'Faire cuire un œuf au plat dans le beurre.',
      'Poser l\'œuf au plat sur le croque-monsieur.',
      'Servir immédiatement.',
    ],
  },
  {
    name: 'Porridge aux pommes',
    emoji: '🌾',
    category: 'Snacks',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    isDefault: true,
    ingredients: [
      { foodId: 'flocons-avoine', foodName: 'Flocons d\'avoine', quantity: 120, unit: 'g' },
      { foodId: 'lait', foodName: 'Lait', quantity: 300, unit: 'ml' },
      { foodId: 'pomme', foodName: 'Pomme', quantity: 1, unit: 'unité' },
      { foodId: 'miel', foodName: 'Miel', quantity: 20, unit: 'g' },
      { foodId: 'cannelle', foodName: 'Cannelle', quantity: 2, unit: 'g' },
    ],
    instructions: [
      'Porter le lait à frémissement avec la cannelle.',
      'Ajouter les flocons d\'avoine, cuire 5 min en remuant.',
      'Râper la pomme, l\'incorporer ou la disposer dessus.',
      'Servir avec un filet de miel.',
    ],
  },

  // ─── BOISSONS ─────────────────────────────────────────────
  {
    name: 'Limonade maison',
    emoji: '🍋',
    category: 'Boissons',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'citron', foodName: 'Citron', quantity: 4, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 80, unit: 'g' },
    ],
    instructions: [
      'Faire un sirop avec sucre et 200 ml d\'eau chaude, refroidir.',
      'Presser les citrons, mélanger avec le sirop refroidi.',
      'Compléter avec 800 ml d\'eau froide et de la glace.',
      'Servir bien frais.',
    ],
  },
  {
    name: 'Smoothie mangue banane',
    emoji: '🥭',
    category: 'Boissons',
    servings: 2,
    prepTime: 5,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'banane', foodName: 'Banane', quantity: 2, unit: 'unité' },
      { foodId: 'orange', foodName: 'Orange', quantity: 2, unit: 'unité' },
      { foodId: 'yaourt', foodName: 'Yaourt nature', quantity: 1, unit: 'unité' },
      { foodId: 'miel', foodName: 'Miel', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Presser les oranges.',
      'Mixer bananes avec le jus d\'orange et le yaourt.',
      'Ajouter le miel selon les goûts.',
      'Servir immédiatement avec de la glace.',
    ],
  },
  {
    name: 'Chocolat chaud maison',
    emoji: '🍫',
    category: 'Boissons',
    servings: 2,
    prepTime: 2,
    cookTime: 8,
    isDefault: true,
    ingredients: [
      { foodId: 'lait', foodName: 'Lait', quantity: 400, unit: 'ml' },
      { foodId: 'chocolat-noir', foodName: 'Chocolat noir', quantity: 80, unit: 'g' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 20, unit: 'g' },
      { foodId: 'vanille', foodName: 'Extrait de vanille', quantity: 3, unit: 'ml' },
    ],
    instructions: [
      'Chauffer le lait sans le faire bouillir.',
      'Casser le chocolat en morceaux et le faire fondre dans le lait chaud.',
      'Ajouter sucre et vanille, fouetter vigoureusement.',
      'Servir bien chaud avec une pincée de cannelle si désiré.',
    ],
  },
  {
    name: 'Thé glacé maison',
    emoji: '🍵',
    category: 'Boissons',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    isDefault: true,
    ingredients: [
      { foodId: 'citron', foodName: 'Citron', quantity: 2, unit: 'unité' },
      { foodId: 'sucre', foodName: 'Sucre', quantity: 60, unit: 'g' },
      { foodId: 'miel', foodName: 'Miel', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Infuser 4 sachets de thé dans 1 L d\'eau chaude 5 min.',
      'Ajouter sucre et miel, mélanger jusqu\'à dissolution.',
      'Laisser refroidir, ajouter le jus des citrons.',
      'Servir avec beaucoup de glace et des rondelles de citron.',
    ],
  },
  {
    name: 'Jus de fruits maison',
    emoji: '🍊',
    category: 'Boissons',
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    isDefault: true,
    ingredients: [
      { foodId: 'orange', foodName: 'Orange', quantity: 4, unit: 'unité' },
      { foodId: 'citron', foodName: 'Citron', quantity: 1, unit: 'unité' },
      { foodId: 'miel', foodName: 'Miel', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Presser les oranges et le citron.',
      'Ajouter le miel et mélanger.',
      'Servir immédiatement pour préserver les vitamines.',
    ],
  },
];
